Create Job Role Backend
cormac-larkin-kainos/Floor_Is_Java_Backend pull request #21
Opened 2023-11-21 14:05 UTC by JonnyEvans99

2023-11-21 14:10 UTC, eoinmcbennett approved these changes

2023-11-21 14:21 UTC, shaunganley requested changes
missing unit tests for validator

2023-11-21 14:21 UTC, shaunganley commented on src/main/java/org/kainos/ea/cli/Capability.java
> +    }
don't need empty constructor

2023-11-21 14:21 UTC, shaunganley commented on src/main/java/org/kainos/ea/cli/JobBand.java
> +    }
don't need empty constructor

2023-11-21 14:21 UTC, shaunganley commented on src/main/java/org/kainos/ea/core/JobValidator.java
> +        }
don't return null here as it won't get to the checks below

2023-11-21 14:21 UTC, shaunganley commented on src/main/java/org/kainos/ea/core/JobValidator.java
> +        }
don't return null here as it won't get to the checks below

2023-11-21 14:21 UTC, shaunganley commented on src/test/java/org/kainos/ea/controller/JobControllerUnitTest.java
> +    void createJobRole_shouldReturn500Response_whenJobRoleServiceThrowsActionFailedException() throws ProjectException, SQLException {
need another test for ProjectException being thrown from service

2023-11-21 14:21 UTC, shaunganley commented on src/test/java/org/kainos/ea/integration/JobControllerIntegrationTest.java
>      }
need an integration test for new post endpoint. 1 for successful create and 1 for validation error scenario

2023-11-21 14:21 UTC, shaunganley commented on src/test/java/org/kainos/ea/service/JobBandServiceUnitTest.java
> +    void getAllJobBands_shouldReturnListOfJobBands_whenDaoReturnsListOfJobBands() throws SQLException, FailedToGetJobBandsException {
need 2 more tests for exception scenarios

2023-11-21 14:21 UTC, shaunganley commented on src/test/java/org/kainos/ea/service/JobServiceUnitTest.java
> +    void createJobRole_shouldThrowProjectException_whenValidationFails() throws SQLException, ProjectException {
this test isn't checking if validation fails. you should be mocking your validator and checking each possible scenario

2023-11-22 14:18 UTC, shaunganley requested changes

2023-11-22 14:18 UTC, shaunganley commented on src/test/java/org/kainos/ea/integration/JobControllerIntegrationTest.java
> +    JobController jobController = new JobController(jobService);
not an integration test if you're mocking the dependencies, this makes it a unit test

2023-11-22 14:18 UTC, shaunganley commented on src/test/java/org/kainos/ea/integration/JobControllerIntegrationTest.java
> +        Response response = jobController.createJobRole(jobRequest);
not an integration test if you're calling the method, you need to call the URL

2023-11-22 14:18 UTC, shaunganley commented on src/test/java/org/kainos/ea/integration/JobControllerIntegrationTest.java
> +        Response response = jobController.createJobRole(jobRequest);
not an integration test if you're calling the method, you need to call the URL

2023-11-22 14:18 UTC, shaunganley commented on src/test/java/org/kainos/ea/integration/JobControllerIntegrationTest.java
> +        Response response = jobController.createJobRole(jobRequest);
not an integration test if you're calling the method, you need to call the URL

2023-11-22 14:18 UTC, shaunganley commented on src/test/java/org/kainos/ea/validator/ValidatorUnitTest.java
> +            JobRequest validJob = mock(JobRequest.class);
you don't need to mock this out, just create an instance of it and pass it in

2023-11-22 14:18 UTC, shaunganley commented on src/test/java/org/kainos/ea/validator/ValidatorUnitTest.java
> +        JobRequest emptyJobTitle = mock(JobRequest.class);
you don't need to mock this out, just create an instance of it and pass it in

2023-11-22 14:18 UTC, shaunganley commented on src/test/java/org/kainos/ea/validator/ValidatorUnitTest.java
> +        JobRequest jobTitleTooBig = mock(JobRequest.class);
you don't need to mock this out, just create an instance of it and pass it in

2023-11-22 14:18 UTC, shaunganley commented on src/test/java/org/kainos/ea/validator/ValidatorUnitTest.java
> +        JobRequest invalidCapabilityID = mock(JobRequest.class);
you don't need to mock this out, just create an instance of it and pass it in

2023-11-22 14:18 UTC, shaunganley commented on src/test/java/org/kainos/ea/validator/ValidatorUnitTest.java
> +        JobRequest invalidCapabilityID = mock(JobRequest.class);
you don't need to mock this out, just create an instance of it and pass it in

2023-11-22 14:18 UTC, shaunganley commented on src/test/java/org/kainos/ea/validator/ValidatorUnitTest.java
> +        JobRequest jobSpecTooLong = mock(JobRequest.class);
you don't need to mock this out, just create an instance of it and pass it in

2023-11-22 14:18 UTC, shaunganley commented on src/test/java/org/kainos/ea/validator/ValidatorUnitTest.java
> +        JobRequest jobSpecEmpty = mock(JobRequest.class);
you don't need to mock this out, just create an instance of it and pass it in

2023-11-22 14:18 UTC, shaunganley commented on src/test/java/org/kainos/ea/validator/ValidatorUnitTest.java
> +        JobRequest jobURLEmpty = mock(JobRequest.class);
you don't need to mock this out, just create an instance of it and pass it in

2023-11-22 14:18 UTC, shaunganley commented on src/test/java/org/kainos/ea/validator/ValidatorUnitTest.java
> +        JobRequest jobURLTooLong = mock(JobRequest.class);
you don't need to mock this out, just create an instance of it and pass it in

2023-11-22 15:25 UTC, shaunganley approved these changes

2023-11-23 15:58 UTC, merged